---
framework: jasmine
postMerge:
  pattern:
    - "./i18n/spec/*.js"
    - "./i18n/ucd/spec/*.js"
  env:
    DOLLAR: ${{ secrets.DOLLAR }}
preMerge:
  pattern:
    - "./i18n/spec/*.js"
    - "./i18n/ucd/spec/*.js"
preRun:
     command:
        - wget https://www.python.org/ftp/python/3.8.3/Python-3.8.3.tgz
        - tar -zxvf Python-3.8.3.tar.gz
        - cd Python-3.8.3 && mkdir ~/.localpython && ./configure --prefix=/home/nucleus/.localpython
        - make && make install
        - yarn install
postRun:
     command:
        - yarn --version
nodeVersion: 14.16.1
version: 1.0.0
