---
framework: jasmine
postMerge:
  pattern:
    - "./i18n/spec/*.js"
    - "./i18n/ucd/spec/*.js"
  env:
    DOLLAR: ${{ secrets.DOLLAR }}
preMerge:
  pattern:
    - "./i18n/spec/*.js"
    - "./i18n/ucd/spec/*.js"
preRun:
     command:
        - curl https://pyenv.run | bash
        - pyenv install 3.8.3
        - pyenv global 3.8.3
        - yarn install
postRun:
     command:
        - yarn --version
nodeVersion: 14.16.1
version: 1.0.0
